version: "3.0"
services:
  openai:
    restart: always
    command: ["npm", "run", "openai"]
    build: .
    env_file: .env
    ports:
      - "8080:8080"
  mailer:
    restart: always
    build: .
    env_file: .env
  postgres:
    image: postgres
    ports:
      - "7755:5432"
    env_file:
      - .env
